import { LEVELS } from "./levels";
import { rankFor, type CareerSave } from "./garage";
import { listMissions, MISSION_COUNT, missionHint } from "./missions";
import type { HudState } from "./types";

export function blankHud(save: CareerSave, patch: Partial<HudState> = {}): HudState {
  const snap = {
    levelIndex: 0,
    keys: 0,
    totalKeys: 1,
    coins: 0,
    totalCoins: 1,
    deaths: 0,
    clock: 0,
    stomps: 0,
    powers: 0,
    won: false,
    grabbedStar: false,
    grabbedGrow: false,
    grabbedNation: false,
    grabbedReplevin: false,
    grabbedMusic: false,
    grabbedElite: false,
    grabbedJohn: false,
    grabbedFidelity: false,
    save,
  };
  return {
    screen: "title",
    levelIndex: 0,
    levelName: LEVELS[0].name,
    kicker: LEVELS[0].kicker,
    coins: 0,
    totalCoins: LEVELS[0].coins.length,
    pesoCoins: 0,
    totalPesoCoins: LEVELS[0].pesos.length,
    deaths: 0,
    hasCheckpoint: false,
    unlocked: save.unlocked,
    best: save.best,
    bestTime: save.bestTime,
    banner: "",
    progress: 0,
    clock: 0,
    record: false,
    pesos: 0,
    warranty: false,
    grow: false,
    buffs: [],
    popup: null,
    cars: save.cars,
    equipped: save.equipped,
    rank: rankFor(save),
    careerKeys: save.careerKeys,
    careerPesos: save.careerPesos,
    missions: listMissions(snap),
    missionsDone: save.missions.length,
    missionsTotal: MISSION_COUNT,
    missionHint: missionHint(snap),
    stompLot: 0,
    mode: "lots",
    stars: save.stars,
    rushBest: save.rushBest,
    survivalBest: save.survivalBest,
    invadersBest: save.invadersBest,
    dealBest: save.dealBest,
    cellsBest: save.cellsBest,
    score: 0,
    wave: 0,
    padAction: "Jump",
    padExtra: null,
    outfits: save.outfits ?? ["jacket"],
    equippedOutfit: save.equippedOutfit ?? "jacket",
    combo: 0,
    comboMax: 0,
    comboHeat: 0,
    dealName: "",
    dealBuy: 0,
    dealSell: 0,
    dealProfit: 0,
    ...patch,
  };
}
